from .clip_adapter import CLIPAdapter
from .clip_adapter_origin import OriginCLIPAdapter
from .cocoop import CoCoOp
from .coop import CoOp
from .coprompt import CoPrompt
from .ft_clip import FinetuneCLIP
from .kgcoop import KgCoOp
from .kgdept import KgDePT
from .prograd import ProGrad
from .promptsrc import PromptSRC
from .maple import MaPLe
from .tcp import TCP
from .zsclip import ZeroShotCLIP